[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "caddy run --config /assets/Caddyfile --adapter caddyfile"
restartPolicyType = "on_failure"
healthcheckPath = "/"
healthcheckTimeout = 300
